# Generated by Django 6.0.4 on 2026-05-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('OPERADOR', 'Operador (atención)'), ('MEDICO', 'Médico'), ('PACIENTE', 'Paciente')], default='PACIENTE', max_length=20, verbose_name='rol'),
        ),
    ]
