# Generated by Django 6.0.4 on 2026-05-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='certificado',
            field=models.FileField(blank=True, help_text='PDF o imagen asociada a la cita (paciente).', null=True, upload_to='certificados_cita/%Y/%m/', verbose_name='certificado digital'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='certificado_notas',
            field=models.TextField(blank=True, help_text='Datos adicionales que deben figurar con el certificado.', verbose_name='notas del certificado'),
        ),
    ]
